-- Queryergebnis:
-- Finden Sie die Sachbearbeiter, deren durchschnittliche Bestellungsbearbeitung (Versanddatum - Bestelldatum)
-- mehr als 5% über dem Gesamtdurchschnitt liegt.
--
-- Ergebnisschema:
-- [Bearbeiter(↑)]
--
-- Punkte:
-- 1.0
--

SELECT BESTELLUNG.BEARBEITER
FROM BESTELLUNG JOIN BESTELLPOSTEN ON BESTELLUNG.BESTELL_NR = BESTELLPOSTEN.BESTELL_NR
GROUP BY BEARBEITER
HAVING AVG(DAYS(BESTELLPOSTEN.VERSANDDATUM) - DAYS(BESTELLUNG.BESTELLDATUM)) >
      (SELECT 1.05*AVG(DAYS(BESTELLPOSTEN.VERSANDDATUM) - DAYS(BESTELLUNG.BESTELLDATUM))
      FROM BESTELLUNG JOIN BESTELLPOSTEN ON BESTELLUNG.BESTELL_NR = BESTELLPOSTEN.BESTELL_NR)
