-- Queryergebnis:
-- Finden Sie für jede Versandart die Marke, deren Bestellposten am häufigsten mit dieser Versandart versandt worden sind.
--
-- Ergebnisschema:
-- [Versandart (↑) | Marke | Anzahl]
--
-- Punkte:
-- 1.0
--

SELECT VERSANDART, MARKE, COUNT(VERSANDART) AS ANZAHL
FROM BESTELLPOSTEN BP JOIN ARTIKEL A ON BP.ARTIKEL = A.ARTIKEL_NR
GROUP BY VERSANDART, MARKE
HAVING COUNT(VERSANDART) IN (SELECT MAX(ANZAHL)
FROM(SELECT VERSANDART, COUNT(VERSANDART) AS ANZAHL
FROM BESTELLPOSTEN BP JOIN ARTIKEL A on BP.ARTIKEL = A.ARTIKEL_NR
GROUP BY VERSANDART, MARKE)
GROUP BY VERSANDART)
ORDER BY VERSANDART